---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install common apt packages
  apt: pkg={{ item }} state=latest
  with_items: elk_common_packages
  sudo: yes

- name: ES apt GPG key
  apt_key:
    url='http://packages.elasticsearch.org/GPG-KEY-elasticsearch'
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: ES apt repo
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/{{ elk_elasticsearch.version }}/{{ ansible_os_family|lower }} stable main"
    update_cache=yes
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Install ES apt packages
  apt: pkg=elasticsearch update_cache=yes state=latest
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest
  sudo: yes

- name: Make monit to look after ES
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit/conf.d/elasticsearch.monitrc.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Reload monit

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  sudo: yes
  notify: Restart elasticsearch

- name: ES delete old indexes cron job
  cron:
    name="delete old elasticsearch indexes"
    user="root"
    special_time="daily"
    job="curator delete --disk-space 4"
  sudo: yes
