---

- name: create log generator directory and copy jar.
  shell: mkdir /home/vagrant/log-generator

- name: Install Thin init.d script
  copy: src=log-generator-0.0.1-SNAPSHOT.jar dest=/home/vagrant/log-generator mode=0755
  sudo: yes

# - name: start log generator
#   shell: bash -lc "java -jar /home/vagrant/log-generator/log-generator-0.0.1-SNAPSHOT.jar -n 100 -r 1000 -t 2"
